[package]
name = "rody"
version = "0.1.0"
edition = "2021"


[dependencies]
memmap = "0.7.0"
rand = {version = "0.8.5", features = ["small_rng"]}
thiserror = "1.0.38"

[dev-dependencies]
tempfile = "3.3.0"
